### ISSUE TITLE
issue with datasets

### ISSUE THREAD

**Issue by osinoyan** [ashesknight/tof-mpi-remove#1]
Hi, I have an issue with using the datasets.
Following the instructions, I ran the sample command below:

`python start.py -b 2 -s 200000 -m sample_pyramid_add_kpn -p size384 -k depth_kinect_with_gt_msk -l 0.0004 -t tof_FT3 -i 480 640 -o mean_l1 --addGradient sobel_gradient -g 4 -e 1200
`

And the the tfrecord file _tof_FT3_train.tfrecords_ is missing. 

I tried to run the "conver script" **convert_TF3_dataset.py** but the original dataset _'/userhome/dataset/original/ToF-FlyingThings3D'_ might be missing. I have no idea where you placed the datasets, including the files mentioned in the convert script: _'train_list.txt'_, _'test_list.txt'_... etc.  (Note I have tried to modify the path string, but there seems to be no directory named dataset/original/ you provided)

Should I download the original dataset of ToF_TF3 mannually? If yes, can you provide the correct link to the dataset? Or can you provide more detailed instructions about using the datasets? thank you.

**Comment by gtdong-ustc** [comment]
Yes, because the original data of TOF_TF3 is large, I did not put the data in the format of TFRecords into Google cloud disk. You can download original TOF-FlyingThings3D from **https://drive.google.com/drive/folders/1XASaOfcp3TzQJ0A2fMaXex-0eihha0vg?usp=sharing** and use our conver script to do the conversion.
